# Generated by Django 4.0.5 on 2022-08-07 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_archivos_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='curso',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
